
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ID METODO NUMERO PAREN_DER PAREN_IZQ PUNTO ROBOTinicio : instruccion\n| instruccion inicioinstruccion : declaracion_robot\n| metodo_sin_parametro\n| metodo_con_parametrodeclaracion_robot : ROBOT IDmetodo_sin_parametro : ID PUNTO METODO\n| ID PUNTO METODO PAREN_IZQ PAREN_DERmetodo_con_parametro : ID PUNTO METODO PAREN_IZQ NUMERO PAREN_DER'
    
_lr_action_items = {'ROBOT':([0,2,3,4,5,9,11,13,15,],[6,6,-3,-4,-5,-6,-7,-8,-9,]),'ID':([0,2,3,4,5,6,9,11,13,15,],[7,7,-3,-4,-5,9,-6,-7,-8,-9,]),'$end':([1,2,3,4,5,8,9,11,13,15,],[0,-1,-3,-4,-5,-2,-6,-7,-8,-9,]),'PUNTO':([7,],[10,]),'METODO':([10,],[11,]),'PAREN_IZQ':([11,],[12,]),'PAREN_DER':([12,14,],[13,15,]),'NUMERO':([12,],[14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'inicio':([0,2,],[1,8,]),'instruccion':([0,2,],[2,2,]),'declaracion_robot':([0,2,],[3,3,]),'metodo_sin_parametro':([0,2,],[4,4,]),'metodo_con_parametro':([0,2,],[5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> inicio","S'",1,None,None,None),
  ('inicio -> instruccion','inicio',1,'p_inicio','robotcodig.py',75),
  ('inicio -> instruccion inicio','inicio',2,'p_inicio','robotcodig.py',76),
  ('instruccion -> declaracion_robot','instruccion',1,'p_instruccion','robotcodig.py',80),
  ('instruccion -> metodo_sin_parametro','instruccion',1,'p_instruccion','robotcodig.py',81),
  ('instruccion -> metodo_con_parametro','instruccion',1,'p_instruccion','robotcodig.py',82),
  ('declaracion_robot -> ROBOT ID','declaracion_robot',2,'p_declaracion_robot','robotcodig.py',86),
  ('metodo_sin_parametro -> ID PUNTO METODO','metodo_sin_parametro',3,'p_metodo_sin_parametro','robotcodig.py',97),
  ('metodo_sin_parametro -> ID PUNTO METODO PAREN_IZQ PAREN_DER','metodo_sin_parametro',5,'p_metodo_sin_parametro','robotcodig.py',98),
  ('metodo_con_parametro -> ID PUNTO METODO PAREN_IZQ NUMERO PAREN_DER','metodo_con_parametro',6,'p_metodo_con_parametro','robotcodig.py',119),
]
